// Project data
const PROJECTS = [
  {
    num: '01',
    name: 'Visual search',
    title: 'An AI-powered feature that turns any media into a product discovery surface',
    company: 'Facebook',
    year: '2022',
    blurb: 'When I joined the team, it was a proof-of-concept generating 200K product page views per month. When I left, it was driving 10x that.',
    tags: ['AI', 'Strategy', 'X-team Expansion', 'Framework'],
    type: 'gif',
    media: 'visual-search.mp4',
    accent: ['#FFC2D4', '#FF9A6B'],
  },
  {
    num: '02',
    name: 'Ad Extension & Mosaic',
    title: 'Front-loading ad destination to shorten the conversion journey',
    company: 'Facebook',
    year: '2023~2025',
    blurb: 'How solving "why users are afraid to click ads" led to $31B+ in shipped revenue and an architecture for what Facebook ads look like next.',
    tags: ['Strategy', 'System architecture', 'Shipped impact', 'Designed with Data'],
    type: 'duo',
    media: 'ad-extension-mosaic.mp4',
    media2: 'mosaic-ad-mock.png',
    accent: ['#D8C4F5', '#FFC2D4'],
  },
  {
    num: '03',
    name: 'Marketplace Chaining',
    title: 'Bringing immersive chaining to Marketplace',
    company: 'Facebook',
    year: '2026',
    blurb: "Bigger ads don't always mean better performance — at least not on Marketplace. So I reframed a stuck monetization problem into a new surface strategy.",
    tags: ['Commerce', 'Strategy', 'Problem Reframing', 'X-Org Navigation'],
    type: 'gif',
    media: 'marketplace-chaining.mp4',
    accent: ['#B8A4E8', '#FFD4B8'],
  },
  {
    num: '04',
    name: 'Ad experience personalization',
    title: "Deliver the right ad experience based on user's preference over time AND intent in the time.",
    company: 'Facebook',
    year: '2024',
    blurb: 'I saw two UX opportunities hitting the same system from different angles, connected them into one strategy, and unlocked format changes the org had never been able to ship.',
    tags: ['Strategy', 'System architecture', 'ML intervention'],
    type: 'diagram',
    media: 'ad-personalization-graph.png',
    accent: ['#A8E0D4', '#C8A8E0'],
  },
  {
    num: '05',
    name: 'Ad format library',
    title: "Codifying Facebook's ad format ecosystem",
    company: 'Facebook',
    year: '2022',
    blurb: 'I built a microsite that turned fragmented ad format knowledge — across audit findings, data insights, and UXR — into the design backbone for ad strategy across family of apps.',
    tags: ['Ad format', 'Audit', 'Design system', 'Principles'],
    type: 'video',
    media: 'ad-format-library.mp4',
    accent: ['#FFB088', '#C896F0'],
  },
  {
    num: '06',
    name: 'Story end card',
    title: 'Turning the dead-end of story viewing into a creation moment.',
    company: 'Messenger & Facebook',
    year: '2019',
    blurb: "My very first project launch at Meta — shipped 6 years ago, but still live today (because turning it off would cost 250M story views per day)!",
    tags: ['Social', 'Mobile', 'Growth'],
    type: 'gif',
    media: 'stories-end-card.gif',
    accent: ['#FFD4B8', '#FFC2D4'],
  },
];

window.PROJECTS = PROJECTS;
